"""Created refresh_token table, and removed refresh_token column from users table

Revision ID: 30917b2ba890
Revises: c18fbcddc111
Create Date: 2024-08-22 06:44:08.816209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30917b2ba890'
down_revision: Union[str, None] = 'c18fbcddc111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###
