"""Created watchlists table

Revision ID: 7b4e4873aed2
Revises: 30917b2ba890
Create Date: 2024-08-26 08:34:55.145922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4e4873aed2'
down_revision: Union[str, None] = '30917b2ba890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('watchlists', sa.Column('items', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('watchlists', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'watchlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.drop_column('watchlists', 'is_private')
    op.drop_column('watchlists', 'items')
    op.drop_column('watchlists', 'user_id')
    # ### end Alembic commands ###
