"""modified items column in watchlists table to accept an integer array

Revision ID: f23a4fc30524
Revises: 38e5132cbbe5
Create Date: 2024-09-01 16:05:20.377769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f23a4fc30524"
down_revision: Union[str, None] = "38e5132cbbe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "watchlists",
    #     "items",
    #     existing_type=postgresql.ARRAY(sa.VARCHAR()),
    #     type_=sa.ARRAY(sa.Integer()),
    #     nullable=False,
    # )

    # op.alter_column(
    #     "watchlists",
    #     "items",
    #     type_=sa.ARRAY(sa.Integer),
    #     existing_type=None,
    #     existing_nullable=True,
    #     using="items::integer[]",
    # )
    op.execute(
        "ALTER TABLE watchlists ALTER COLUMN items TYPE INTEGER[] USING items::integer[];"
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "watchlists",
        "items",
        existing_type=sa.ARRAY(sa.Integer()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    # ### end Alembic commands ###
