"""set nullable to true on items col watchlists table

Revision ID: 045bc614d4d8
Revises: f23a4fc30524
Create Date: 2024-10-14 15:12:28.907320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045bc614d4d8'
down_revision: Union[str, None] = 'f23a4fc30524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
