"""add_token_version

Revision ID: 45758ff7e805
Revises: dd259bf23e66
Create Date: 2026-05-19 17:09:52.451223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45758ff7e805'
down_revision: Union[str, None] = 'dd259bf23e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET token_version = 1 WHERE token_version IS NULL")
    op.alter_column('users', 'token_version', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
